### ISSUE TITLE
404 when trying to fetch libsjs dependencies

### ISSUE THREAD

**Issue by peacememories** [Elphel/meta-elphel393#2]
When trying to build libsjs the following error occurs:

```
ERROR: Fetcher failure: Fetch command failed with exit code 8, output:
http://mirror.elphel.com/elphel393_mirror/jquery-2.2.3.js:
2017-02-22 15:59:18 ERROR 404: Not Found.

ERROR: Function failed: Fetcher failure for URL: 'http://mirror.elphel.com/elphel393_mirror/jquery-2.2.3.js;md5sum=aacc43d6f308fa362ac85e3f4fb2b30c'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/vagrant/elphel393/poky/build/tmp/work/cortexa9-neon-poky-linux-gnueabi/libsjs/20160419-r0/temp/log.do_fetch.13840
ERROR: Task 572 (/home/vagrant/elphel393/meta/meta-elphel393/recipes-support/libsjs/libsjs.bb, do_fetch) failed with exit code '1'
```

Making some changes in the bb file seems to fix the problem (patch file made by a colleague, not myself)
[libsjs.bb.patch.zip](https://github.com/Elphel/meta-elphel393/files/794091/libsjs.bb.patch.zip)

**Comment by okdzhimiev** [comment]
We have asked our provider to update our server yesterday - hopefully it will be fixed soon - atm, mirror.elphel.com has most of the files unavailable via the webserver.

**Comment by okdzhimiev** [comment]
Fixed. 
Switched from our broken mirror to original sources.
